version: '0.1'
services:
  database:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "auth"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    ports:
        - '5432:5432'
